version: '3.8'

services:
  vault:
    image: hashicorp/vault-enterprise:1.19.5-ent
    container_name: vault-dev
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_API_ADDR: http://0.0.0.0:8200
      VAULT_LICENSE: ${VAULT_LICENSE}
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id=myroot -dev-listen-address=0.0.0.0:8200
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - vault-data:/vault/data
      - vault-logs:/vault/logs

volumes:
  vault-data:
  vault-logs:
