services:
  # Vault Transform Service
  vault:
    image: hashicorp/vault-enterprise:1.19.5-ent
    container_name: vault-dev
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_API_ADDR: http://0.0.0.0:8200
      VAULT_LICENSE: ${VAULT_LICENSE}
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id=myroot -dev-listen-address=0.0.0.0:8200
    volumes:
      - vault-data:/vault/data
      - vault-logs:/vault/logs

  # BigQuery Simulator
  bigquery-simulator:
    image: ghcr.io/goccy/bigquery-emulator:0.4.3
    platform: linux/amd64
    container_name: bigquery-simulator
    restart: unless-stopped
    ports:
      - "9050:9050"
      - "9060:9060"
    environment:
      - PROJECT_ID=${PROJECT_ID:-test-project}
    command: 
      - bigquery-emulator
      - --project=${PROJECT_ID:-test-project}
      - --port=9050
      - --log-level=info
    volumes:
      - ../config/bigquery-data:/data
      - bigquery-storage:/tmp/bigquery-emulator
    profiles:
      - bigquery
      - full

  # Cloud Function Local Development (Functions Framework)
  cloud-function-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: cloud-function-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=myroot
      - VAULT_TRANSFORM_ROLE=creditcard-transform
      - FUNCTIONS_SIGNATURE_TYPE=http
    depends_on:
      - vault
    volumes:
      - ../src:/workspace
      - /workspace/__pycache__
    profiles:
      - bigquery
      - full

volumes:
  vault-data:
  vault-logs:
  bigquery-storage:
