# BigQuery Simulator Data Configuration
# This YAML file defines the initial dataset and table structure for testing

- project: test-project
  datasets:
    - id: fraud_detection
      tables:
        - id: transactions
          columns:
            - name: transaction_id
              type: STRING
              mode: REQUIRED
            - name: encrypted_credit_card
              type: STRING
              mode: REQUIRED
            - name: amount
              type: FLOAT64
              mode: REQUIRED
            - name: merchant
              type: STRING
              mode: REQUIRED
            - name: transaction_date
              type: TIMESTAMP
              mode: REQUIRED
            - name: is_fraud
              type: BOOLEAN
              mode: NULLABLE
          data:
            - transaction_id: "TXN001"
              encrypted_credit_card: "2691290006800783"
              amount: 150.75
              merchant: "Amazon"
              transaction_date: "2025-08-08T10:30:00"
              is_fraud: false
            - transaction_id: "TXN002"
              encrypted_credit_card: "2872860725189259"
              amount: 89.99
              merchant: "Target"
              transaction_date: "2025-08-08T11:15:00"
              is_fraud: false
